version: '3.9'
services:
  react:
    image: react
    container_name: react
    restart: always
    links:
      - nginx
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    restart:  always
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d